FROM python:3

WORKDIR /app

RUN git clone https://github.com/AgnidDrage/Parcial.1.git

WORKDIR /app/Parcial.1/59081.Sanchez.Toledo.Mariano

CMD ["python3", "test_book.py"] && ["python3", "test_members.py"]
